### ISSUE TITLE
Django 1.4 needs 832caa41ec7b74d332c01d134f2ce0dc0f2f4afb

### ISSUE THREAD

**Issue by william-gr** [klipstein/dojango#101]
Hello,

Django 1.4 needs 832caa41ec7b74d332c01d134f2ce0dc0f2f4afb,
would you mind preparing a new release based on trunk, now that django 1.4 has been released?

Thanks

**Comment by klipstein** [comment]
Hi William,

will prepare a new release today and also look into the pull requests you've provided.

Regards, Tobias

**Comment by klipstein** [comment]
Just pushed a new version to pypi: http://pypi.python.org/pypi/dojango/0.5.5

Thanks for the reminder.

**Comment by william-gr** [comment]
Hi,

Thank you very much!
