### ISSUE TITLE
VALUE attribute for DateField has wrong format 

### ISSUE THREAD

**Issue by mpasternak** [klipstein/dojango#103]
With Dojo 1.7.2, there is a problem with DateField.

This is the small example that demonstrates this problem - just use "manage.py runserver" - https://github.com/mpasternak/dojango-problem-datefield

When the DateField has an initial value, django/dojango render the value in the HTML according to LANGUAGE_CODE from settings.py . Unfortunatley, this does not work for Dojo, as the field with initial value for example "29.05.2012" will be removed from the widget as soon as the dojo code finishes loading.

... if the date field's VALUE is for example "2012-05-29", everything works fine - after dojo code finishes loading, the date in the widget is not being erased and it is displayed according to current locale.

**Comment by mpasternak** [comment]
I created a silly but working fix for it here: https://github.com/mpasternak/dojango -- https://github.com/mpasternak/dojango/commit/c61a6f15536a362689aa8d8f484c2f11ea29ecf8

**Comment by klipstein** [comment]
Dojo always expects the US date format and does the formatting on the client-side then. Thanks for pointing that out.

**Comment by mpasternak** [comment]
Thanks for the quickiest fix!

2012/6/1 klipstein <
reply@reply.github.com

> Dojo always expects the US date format and does the formatting on the
> client-side then. Thanks for pointing that out.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/klipstein/dojango/issues/103#issuecomment-6069565

## 

Pozdrawiam,
Micha³ Pasternak
+48 793 66 87 33
