### ISSUE TITLE
BASE_DOJO_ROOT directory does not exist

### ISSUE THREAD

**Issue by rhunwicks** [klipstein/dojango#114]
If you install Dojango from Github using pip with a `requirements.txt` line similar to:

```
git+https://github.com/klipstein/dojango.git@master
```

and then run `./manage.py dojoload --dojo_version=1.9.1` the download fails because it is trying to download into `BASE_DOJO_ROOT` which defaults to `BASE_MEDIA_ROOT + "/src"` but the `src` sub-directory does not exist.

**Comment by klipstein** [comment]
Fixed with https://github.com/klipstein/dojango/commit/fbd6ea5170c4364213ab3fe69d0ffa17a4c4b47d and https://github.com/klipstein/dojango/commit/1939a39440265f12b6708e14b581642c46e4d7a2. Thanks for reporting that issue.
