### ISSUE TITLE
89 - Dojango is not a python package 

### ISSUE THREAD

**Issue by klipstein** [klipstein/dojango#87]
<pre>
<b>What steps will reproduce the problem?</b>
1. pip install svn+<a href="http://dojango.googlecode.com/svn/trunk/dojango" rel="nofollow">http://dojango.googlecode.com/svn/trunk/dojango</a>

<b>What is the expected output? What do you see instead?</b>

Package is not installed - Doajngo is not a python package.

Downloading/unpacking svn+<a href="http://dojango.googlecode.com/svn/trunk/dojango" rel="nofollow">http://dojango.googlecode.com/svn/trunk/dojango</a>
  Checking out svn repository <a href="http://dojango.googlecode.com/svn/trunk/dojango" rel="nofollow">http://dojango.googlecode.com/svn/trunk/dojango</a> to /tmp/pip-nAXA85-build
  Running setup.py egg_info for package from svn+<a href="http://dojango.googlecode.com/svn/trunk/dojango" rel="nofollow">http://dojango.googlecode.com/svn/trunk/dojango</a>
    Traceback (most recent call last):
      File &quot;&lt;string&gt;&quot;, line 14, in &lt;module&gt;
    IOError: [Errno 2] No such file or directory: '/tmp/pip-nAXA85-build/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File &quot;&lt;string&gt;&quot;, line 14, in &lt;module&gt;

IOError: [Errno 2] No such file or directory: '/tmp/pip-nAXA85-build/setup.py'

---

Command python setup.py egg_info failed with error code 1

<b>What version of the product are you using? On what operating system?</b>

1.1.0 on ubuntu 10.04

<b>Please provide any additional information below.</b>

I was wondering if it was possible to make dojango a python package i.e. installable with pip? I have been very happily using dojango in django applications on a shared hosted environment. Now I am moving to a PaaS (dotcloud) where all requirements are managed with pip but I cant install dojango as its not a python package.

</pre></br>Original link: http://code.google.com/p/dojango/issues/detail?id=89

**Comment by klipstein** [comment]
just try it with (without the dojango subfolder): 

```
pip install svn+http://dojango.googlecode.com/svn/trunk
```

But dojango won't be maintainted on this SVN server anymore and it would be better if you already pick up the project from GitHub:

```
pip install git+git://github.com/klipstein/dojango.git
```

**Comment by bettlebrox** [comment]
Thanks Tobias,

I should have noticed that. I am working off git using pip install now. no problems.
