### ISSUE TITLE
Caught TypeError while rendering: isinstance() arg 2 must be a class, type, or tuple of classes and types

### ISSUE THREAD

**Issue by emacsway** [klipstein/dojango#91]
/media1/home/devel/django_sites/tripster/website/dojango/util/**init**.py in _any, line 130

in template:
isDebug':{{ DOJANGO.DEBUG|json }},

Solution:

<pre>
git diff
diff --git a/dojango/util/__init__.py b/dojango/util/__init__.py
index 954a6df..e3ad050 100644
--- a/dojango/util/__init__.py
+++ b/dojango/util/__init__.py
@@ -127,7 +127,7 @@ def json_encode(data):
             ret = _model(data)
         elif appengine and isinstance(data, appengine.ext.db.Model):
             ret = _googleModel(data)
-        elif isinstance(data, ObjectId):
+        elif ObjectId and isinstance(data, ObjectId):
             ret = str(data)
         # here we need to encode the string as unicode (otherwise we get utf-16 in the json-response)
         elif isinstance(data, basestring):
</pre>

**Comment by klipstein** [comment]
Oups. Seems I've not fixed that right yesterday. Will care about it now.
